# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fe41987d8ec87a763e11f80504b5ab32ecad5feb1de5b0ec67b64b7315f924e8ff62bae3e9df3f7859468421fb2f45ba74fa9b7a5ea23e5658198efd180c6b2

test:
  secret_key_base: eda19e2928f6abd7c1257b49b11c4a26610e260aff4171edb058e1e0113e5911ab39fa114c3db113f2bfd230cc406e93916ceadca70129bfb85d51cce3178917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
